pages:
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get install -y emacs
  script:
    - mkdir -p public
    - emacs -Q --script build-site.el
    - emacs -Q --script generate-sidebar.el
  artifacts:
    paths:
      - public
  only:
    - main
